name = "BVARForecasting"
uuid = "f8f414a2-bec5-4b35-a31f-a19c1af3a348"
authors = ["Parker Sheppard <parker.sheppard@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.7.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
